CREATE TABLE [dbo].[GearSizes]
(
	[GearID] TINYINT NOT NULL,
	CONSTRAINT [FK_GearSizes_RockClimbingGearID] FOREIGN KEY ([GearID]) REFERENCES [Gear]([ID]),

	[ID] TINYINT NOT NULL PRIMARY KEY,
	[EnglishFullName] VARCHAR(100) NOT NULL,
)
