CREATE TABLE [dbo].[UserDMs]
(
	[UserFromID] INT NOT NULL,
	CONSTRAINT [FK_UserDMs_Users_From] FOREIGN KEY ([UserFromID]) REFERENCES [Users]([ID]),
	
	[UserToID] INT NOT NULL,
	CONSTRAINT [FK_UserDMs_Users_To] FOREIGN KEY ([UserToID]) REFERENCES [Users]([ID]),

	[DirectMessageID] TINYINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Time] DATETIME NOT NULL,
	[Comments] VARCHAR(250) NOT NULL,
)
