CREATE TABLE [dbo].[UserDMs]
(
	[UserFromID] INT NOT NULL,
	CONSTRAINT [FK_UserDMs_Users_From] FOREIGN KEY ([UserFromID]) REFERENCES [Users]([ID]),
	
	[UserToID] INT NOT NULL,
	CONSTRAINT [FK_UserDMs_Users_To] FOREIGN KEY ([UserToID]) REFERENCES [Users]([ID]),

	[DirectMessageID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Time] DATETIME NOT NULL DEFAULT GETDATE(),
	[Seen] BIT NOT NULL DEFAULT 0,
	[Message] VARCHAR(2500) NOT NULL,

	CONSTRAINT [CK_UserDMs_CannotMessageSelf] CHECK (not UserFromID = UserToID)
)
